### ISSUE TITLE
bad return code

### ISSUE THREAD

**Issue by sbh7600** [rakshasa/rtorrent#1024]
Hello, 

im trying to use rtorrent and it works great but:

1. im downloading from another tracker with one custom .rc file (works)
https://pastebin.com/fKXzLHb6 (.rc file)

2. then i have made another .rc file. to handle the things i upload to my primary site
https://pastebin.com/w66EJqxV (.rc file)

but when download is done, it gives me a 'bad return code' how come, do i have a error in the 'method.set_key'

or what is going one here.

One more thing, the upload script works when i run it manuel.

**Comment by piramiday** [comment]
you should code your bash script with more in-depth debugging:
- abundant `echo` commands to make sure variables are what you expect,
- several error checks to make sure the workflow is as expected,
- unique exit codes so that you can pinpoint the error exactly.

once rtorrent complains about a non-zero exit code, you can then easily understand what happened in your script.
make sure you have set your executable bits and are invoking the script correctly.

**Comment by sbh7600** [comment]
the script are working now also rtorrent :) did some execute.log recon. and could see the errors :)

**Comment by piramiday** [comment]
great! if that's the case, please close this issue. :+1:
