### ISSUE TITLE
Torrents loaded via watch_directory lose "comment" info in 0.9.8

### ISSUE THREAD

**Issue by YouSeeMeToo** [rakshasa/rtorrent#1117]
I'm running rtorrent on a remote seedbox, and I use a series of synced watch directories to allow me to select what label is applied to a torrent, and its start state when it's loaded.

Unfortunately, none of the torrents loaded via the watch dirs have the comment field preserved. The tracker I use lists the torrents URL in the comment field, and I often use this to look up information on a torrent, particularly if the name is ambiguous.

**Comment by stickz** [comment]
I can confirm this issue exists. @YouSeeMeToo Did this just start in 0.9.8? Or has it been preset in all versions of rTorrent?

Also, interestingly enough, if the torrent is added via ruTorrent the comment is preserved.

**Comment by kannibalox** [comment]
You may want to double check whatever tool/script/config you're doing the loading with. None of the built-in `load.*` commands interfere with the comment field.

**Comment by stickz** [comment]
Okay then this bug is with ruTorrent and not rTorrent. I'm going to create an issue report over there.

**Comment by zze0s** [comment]
It looks like this is the case for torrents loaded via rutorrent httprpc plugin as well, which seem to just pass it onto the rtorrent backend, and get lost then. It works when uploaded via rutorrent which I assume is because rutorrent saves the full file.

There's no relevant mentions of `comment` found with [code search](https://github.com/search?q=repo%3Arakshasa%2Frtorrent%20comment&type=code) in the project that I can find. Can't find anything in the libtorrent repo either, but maybe github code search is broken.

I isn't `comment` part of any BEPs or the official spec?

**Comment by rakshasa** [comment]
RTorrent doesn't touch extraneous fields in the bencoded object used to add a download, so this is an issue with 3rd party programs imo.
