### ISSUE TITLE
I can't add 82Gb Torrent

### ISSUE THREAD

**Issue by soykot360** [rakshasa/rtorrent#1172]
https://prnt.sc/uwWZwsFfZNGD
Piece Size 16 MiB

**Comment by kannibalox** [comment]
If it's being displayed in ruTorrent, then it's added. If the issue is that it's not starting, you can check for common issues like low disk space and whether the correct permissions are applied to the directories, but otherwise you'll need to provide more information (preferably from rTorrent directly, a screenshot of ruTorrent doesn't help much).

**Comment by soykot360** [comment]
> If it's being displayed in ruTorrent, then it's added. If the issue is that it's not starting, you can check for common issues like low disk space and whether the correct permissions are applied to the directories, but otherwise you'll need to provide more information (preferably from rTorrent directly, a screenshot of ruTorrent doesn't help much).

All permission and settings are ok and disk space is ok
Below 64gb file successfully added and started download
But this 82gb added successfully but it's not downloading
