### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [rakshasa/rtorrent#1288]
Dear rtorrent team, @rakshasa,

It is possible to create a new release build?

The latest is 0.9.8 (2019-07-19):
- https://github.com/rakshasa/rtorrent/releases
- https://github.com/rakshasa/rtorrent/tags

Thanks in advance.

**Comment by s1nistr4** [comment]
The project is dead, hasn't been updated in a year. It could use a fork for anyone that knows C/C++

**Comment by stickz** [comment]
> The project is dead, hasn't been updated in a year. It could use a fork for anyone that knows C/C++

How about a fork that is 40% faster, higher performing, more stable/polished and more secure?
https://github.com/stickz/rtorrent

**Comment by WagnerGMD** [comment]
From another point of view, it's worst for the people which rather a good (official or reliable) release.
Because the both latest [stable rtorrent-v0.9.8](https://github.com/rakshasa/rtorrent/releases/tag/v0.9.8) and the [stable libtorrent-v0.13.8](https://github.com/rakshasa/libtorrent/releases/tag/v0.13.8) were published on the 19 July 2019 (the both are dead since 5 years ago).

Finally there is something : Thank you for the discovery @stickz because I don't know when but one day, i will replace it by an alternative (easy to compile ? Not obvious to choose for example the [qbittorent-nox](https://github.com/qbittorrent/qBittorrent/wiki/Running-qBittorrent-without-X-server-(WebUI-only,-systemd-service-set-up,-Ubuntu-15.04-or-newer)) require the [libtorrent-rasterbar](https://www.libtorrent.org/building.html) which have a very long documentation (which could be also too old)).

PS : I will give you one advice, it will better to read (follow) the [Changelog of xmlrpc-c](https://xmlrpc-c.sourceforge.io/change.html) (basically replace the `super_stable` by the branch `advanced` which is far reliable (around 8 years = only one big trouble).

**Comment by davorb** [comment]
> The project is dead, hasn't been updated in a year. It could use a fork for anyone that knows C/C++

Is it really dead? I see commits from this week on `master`.

**Comment by rakshasa** [comment]
I've started working on rtorrent again, so should see some more activity.

**Comment by stickz** [comment]
@rakshasa I have 3 more very simple pull requests coming to fix some big problems with rTorrent. Afterwards, I would like to kindly request a new release be posted. This will allow Linux operating systems and other platforms to adopt the changes.

1) The first pull request is located here: https://github.com/rakshasa/rtorrent/pull/1291

2) Is a 1 line fix for a critical memory leak with RPC commands.

3) Is a 10 line fix for session file data corruption due to sudden loss of power. 

cc: @anthonyryan1

**Comment by rakshasa** [comment]
Done, let me know ones it's been tested.

**Comment by Neustradamus** [comment]
@rakshasa: Nice to see your comeback.

What have you done?

Do not forget to create a new release for rtorrent:
- https://github.com/rakshasa/rtorrent/releases

And libtorrent too:
- https://github.com/rakshasa/libtorrent/issues/234
- https://github.com/rakshasa/libtorrent/issues/233

I have sent you an e-mail.

**Comment by stickz** [comment]
@Neustradamus We are testing the master branch for libtorrent and rTorrent currently. rakshasa and I are being sponsored by a third party to improve rTorrent. I will advise rakshasa once these changes are tested, so a release can be posted.

**libtorrent**
1. Significant performance improvements to improve throughput and reduce CPU usage.
2. A fix for a torrent client crash with the socket address object.
3. Support for 33 gigabit speed throttles on ruTorrent.

**rTorrent**
1. A fix for a torrent client stack overflow crash with the lockfile buffer.
2. New `trackers.delay_scrape` command for .rtorrent.rc to avoid crashes with thousands of torrents and allow instant startups.
3. A fix for compiling the software with LTO (Link Time Optimizations) for additional performance.
4. A fix for a critical memory leak with RPC commands which may waste an alarming amount of memory.
5. A fix for critical torrent client breakage if a power outage/failure occurs during a session saving interval.

**Comment by rakshasa** [comment]
Since there's no complaints thus far, I'll do a release soon.

**Comment by Neustradamus** [comment]
@stickz, @rakshasa: Thanks for your answers!

@rakshasa: Please look your mailbox, it is important.
Thanks in advance.

**Comment by rakshasa** [comment]
Release is out.

**Comment by davorb** [comment]
@rakshasa i know this issue is closed. just wanted to welcome you back. this has been one of my favorite pieces of software for decades.

**Comment by cemeyer** [comment]
The wiki still mentions 0.9.8 / 0.13.8 as the stable releases.  Is 0.15.1 considered stable?  (Asking if we should push this to Fedora users.)  Thanks.

**Comment by stickz** [comment]
> The [wiki still mentions 0.9.8 / 0.13.8 as the stable releases](https://github.com/rakshasa/rtorrent/wiki#stable). Is 0.15.1 (#1356) considered stable? (Asking if we should push this to Fedora users.) Thanks.

Hi @cemeyer, there's still a few minor issues with `tinyxml2`. I would recommend pushing `0.15.1` with `--with-xmlrpc-c`. Stability wise, it should be better than `0.9.8 / 0.13.8`. Consider revisiting `tinyxml2` for the next release.

**Comment by cemeyer** [comment]
Thanks, @stickz!  We can do that.

**Comment by cemeyer** [comment]
Hm, configure does not actually seem to recognize a with-xmlrpc-c feature.  I see there's some test in scripts/checks.m4, but it doesn't seem to be present in configure.ac like many other TORRENT_WITH_ checks.  Something like:

```
--- configure.ac.orig   2025-01-04 14:58:20.884202189 -0800
+++ configure.ac        2025-01-04 14:57:58.093765630 -0800
@@ -53,6 +53,7 @@

 TORRENT_WITHOUT_STATVFS
 TORRENT_WITHOUT_STATFS
+TORRENT_WITH_XMLRPC_C
 TORRENT_WITH_INOTIFY
```
