### ISSUE TITLE
rtorrent sporadically stops with return code 141

### ISSUE THREAD

**Issue by takeda** [rakshasa/rtorrent#1292]
I recently observed that my rtorrent stops with return code 141, any idea what it could mean? I didn't observe any other message.

I also wasn't too lucky when trying to search source code for that value.

Additional information: rtorrent 0.9.8 running on FreeBSD 14.1

**Comment by rakshasa** [comment]
That would be SIGPIPE, however rtorrent has always been set to ignore.

The issue might be with whatever you're using to run rtorrent.

**Comment by extra** [comment]
If you're using the latest libcurl 8.9.1 it looks like this is due to a bug/regression: https://github.com/termux/termux-packages/issues/21036

Manually applying this patch fixes the issue for me (or you can wait until the next release): https://github.com/curl/curl/commit/3eec5afbd0b6377eca893c392569b2faf094d970

**Comment by takeda** [comment]
Nice find! I just checked and I'm indeed using a version that has this issue and my curl is still one version earlier than this: https://www.freshports.org/commit.php?category=ftp&port=curl&files=yes&message_id=73d53fec20e010a33757af558db532d30c3a085b

So I'm now upgrading curl and closing this issue.

Thank you again for figuring out what it was!
