### ISSUE TITLE
Roadmap & Changelog for rTorrent 0.11.0

### ISSUE THREAD

**Issue by stickz** [rakshasa/rtorrent#1349]
@rakshasa Could we make a roadmap to tag a new version of rTorrent? I'm working with my partners to get the `tinyxml2` changes that @kannibalox made tested and deployed to thousands of clients. We just need a release to make that happen.

### My recommendation for a roadmap is:

**rTorrent:** 
1. Test and merge https://github.com/rakshasa/rtorrent/pull/1347 
2. Test and merge https://github.com/rakshasa/rtorrent/pull/1348

**libtorrent:** 
1. Test and merge https://github.com/rakshasa/libtorrent/pull/281

### Recommended Changelog Includes:

# libtorrent

### Stability Improvements
1. Resolved a crash with Handshake buffer resizing. 
    - https://github.com/rakshasa/libtorrent/pull/254 by @rakshasa 
    - https://github.com/rakshasa/libtorrent/pull/264 by @slingamn 

2. Respect failure intervals for trackers.
    - https://github.com/rakshasa/libtorrent/pull/260 by @rakshasa and @kannibalox 

3. Fix file truncation on resume with fallocate enabled
    - https://github.com/rakshasa/libtorrent/pull/261 by @rakshasa and @jmakovicka

4. Change __sync_* to std::atomic for cross platform compatibility.
    - https://github.com/rakshasa/libtorrent/pull/266 by @rakshasa 
    - https://github.com/rakshasa/libtorrent/pull/267 by @rakshasa 

5. Resolve `Wclass-memaccess` compile warning with `std::memset`.
   - https://github.com/rakshasa/libtorrent/pull/280 by @neheb

### Performance Improvements
1. Only write `uncertain_pieces.timestamp` when necessary.
    - https://github.com/rakshasa/libtorrent/pull/257 by @kannibalox 

2. Use emplace instead of push for `std::array` objects.
    - https://github.com/rakshasa/libtorrent/pull/279 by @neheb

### Code Cleanup
1.  https://github.com/rakshasa/libtorrent/pull/263 by @kannibalox 
2.  https://github.com/rakshasa/libtorrent/pull/262 by @kannibalox 
4.  https://github.com/rakshasa/libtorrent/pull/273 by @kannibalox 
5.  https://github.com/rakshasa/libtorrent/pull/274 by @kannibalox
7.  https://github.com/rakshasa/libtorrent/pull/277 by @kannibalox 
8.  https://github.com/rakshasa/libtorrent/pull/277 by @neheb
9.  https://github.com/rakshasa/libtorrent/pull/282 by @rakshasa
10.  https://github.com/rakshasa/libtorrent/pull/281 by @neheb 

# rTorrent

### Stability Improvements
1. Resolved scgi software crash with SIGPIPE exception.
    - https://github.com/rakshasa/rtorrent/pull/1310 by @stickz
    - https://github.com/rakshasa/rtorrent/pull/1329 by @stickz

2. Various build stability improvements.
    - https://github.com/rakshasa/rtorrent/pull/1317 by @PPN-SD

3. Change __sync_* to std::atomic for cross platform compatibility.
    - https://github.com/rakshasa/rtorrent/pull/1324 by @kannibalox 

4. Resolved a crash with the curl stack during shutdown.
    - https://github.com/rakshasa/rtorrent/pull/1338 by @rakshasa 

5. Resolve `Wclass-memaccess` compile warning with `std::memset`.
   - https://github.com/rakshasa/rtorrent/pull/1344 by @rakshasa

6. Fixed `d.group.name` returning the wrong value.
   - https://github.com/rakshasa/rtorrent/pull/1326 by @trim21

7. Fixed compatibility checks for file types.
   -  https://github.com/rakshasa/rtorrent/pull/1327 by @kannibalox and @rakshasa 

### Tinyxml2 to replace xmlrpc-c
- https://github.com/rakshasa/rtorrent/pull/1322 by @kannibalox and @rakshasa 
- https://github.com/rakshasa/rtorrent/pull/1331 by @kannibalox 
- https://github.com/rakshasa/rtorrent/pull/1348 by @kannibalox 
- https://github.com/rakshasa/rtorrent/pull/1347 by @stickz 

Please configure rTorrent with `--with-xmlrpc-tinyxml2` to enable tinyxml2. It contains 2-3 times performance improvements for small responses and up to 30 times performance improvements for large responses. This is a significant reduction in overhead!

xmlrpc-c:
```
Benchmark               Time             CPU   Iterations
---------------------------------------------------------
small_response       3417 ns         3413 ns       204332
large_response   46159260 ns     46074301 ns           15
```

tinyxml2:
```
Benchmark               Time             CPU   Iterations
---------------------------------------------------------
small_response       1595 ns         1593 ns       462388
large_response    1512614 ns      1509299 ns          463
```

### Code Cleanup
1. https://github.com/rakshasa/rtorrent/pull/1311 by @kannibalox 
2. https://github.com/rakshasa/rtorrent/pull/1312 by @kannibalox 
3. https://github.com/rakshasa/rtorrent/pull/1314 by @rakshasa 
4. https://github.com/rakshasa/rtorrent/pull/1340 by @rakshasa 
5. https://github.com/rakshasa/rtorrent/pull/1343 by @kannibalox 
6. https://github.com/rakshasa/rtorrent/pull/1345 by @rakshasa

**Comment by stickz** [comment]
> why we keep xmlrpc-c anyway?

We need to test tinyxml2 first. I just found 2 problems with it today. 2 pull requests are pending to resolve them. This is a massive change. I'm working on deploying it to thousands of clients on crazy max docker. We need to test test test before we drop it.

**Comment by stickz** [comment]
> also why 0.12.0 instead of 0.11? current version is 0.10, any reason skip 0.11?

You're right! @rakshasa likes to count by 1's for the second number. I've updated the title. Thank you.

**Comment by slingamn** [comment]
Why do you need an upstream release in order to fully test the changes? It seems backwards --- first you should deploy your release candidate, and then if your testing is successful, that would justify an upstream release :-)

**Comment by stickz** [comment]
> Why do you need an upstream release in order to fully test the changes? It seems backwards --- first you should deploy your release candidate, and then if your testing is successful, that would justify an upstream release :-)

Nobody is going to deploy a release candidate. There is no harm done with an upstream release. We can just post a hotfix afterwards if required. We've already done development testing as required. I found 2 bugs with tinyxml2 today. :-)

**Comment by neheb** [comment]
since I got pinged, anyone know what's wrong here? https://github.com/rakshasa/libtorrent/pull/283

**Comment by stickz** [comment]
> since I got pinged, anyone know what's wrong here? [rakshasa/libtorrent#283](https://github.com/rakshasa/libtorrent/pull/283)

I would recommend breaking that down into smaller pull requests, to more effectively find problems.

We'll need your help with https://github.com/rakshasa/libtorrent/pull/281 if rakshasa approves this roadmap to an upstream release. This is a very good time to hit the pause button and ship the work we've done to rTorrent to thousands of users.

**Comment by rakshasa** [comment]
Seems reasonable, I'll check out the tinyxml2 related PRs.

**Comment by rakshasa** [comment]
> > also why 0.12.0 instead of 0.11? current version is 0.10, any reason skip 0.11?
> 
> You're right! @rakshasa likes to count by 1's for the second number. I've updated the title. Thank you.

Just to mess things up I sync'ed both versions to 0.15.0.

**Comment by eli-schwartz** [comment]
> Why do you need an upstream release in order to fully test the changes? It seems backwards --- first you should deploy your release candidate, and then if your testing is successful, that would justify an upstream release :-)

Both release candidates and final releases are useful for testing changes. It's not an "either or" thing. Usually release candidates are only used by people who manually opt in on a person to person basis though. It's absolutely useless to expect release candidates to be automatically rolled out to "thousands of clients" automatically because no one is going to ask, or expect, thousands of people in a specific group to all test something that is explicitly an experimental build.

But e.g. Gentoo would most likely package a release candidate if the package maintainer is made aware of it. And at least a few people would manually enable that release candidate, while also expecting it's their self-elected job to report obscure bugs when they do.

Nonetheless, this is NOT the same as full testing. It is standard operating procedure for software making significant changes (framework, build system, etc) that *need testing*, to provide at least one release cycle where both options are available, so that people can test the changes, and disable them if issues are encountered, without downgrading the software to the previous major.minor release. This is important for the project itself, too, since if people are afraid to upgrade to the new release because of one deal breaker regression then they will not test the other changes and you end up only finding and fixing a single bug per release cycle, which sucks.

Ultimately it's a balance between maintaining old code you don't really want to keep maintaining, and ensuring the software works for the largest number of people. It is *really* easy to keep old code if it's just a big chunk of trivially `#ifdef`ed logic that you can gate behind a configure option. Projects *should* feel encouraged to do precisely that whenever they feel a bit nervous about a change, it is very comforting to know that you can just tell users "no big deal, configure this brand new option off for now and we'll make it work in the next release". Your software still works, it's just the optional new thing that doesn't work. ;)
