### ISSUE TITLE
Enhancement:   implements a daemon mode 

### ISSUE THREAD

**Issue by Lorenz1508** [rakshasa/rtorrent#171]
Hi, love rtorrent

I am missing one thing though, the ability to run  rtorrent  as a daemon but will still function normally under normal conditions. without screen

thanks

**Comment by Lapin0t** [comment]
I think this issue is quite important because lots of people are using it that way (with a webui or another kind of ui). The curse ui is therefore useless and it bugs all the startup scripts (they _work_ but messing with screen or dtach in startup scripts is not quite a good idea). Is it a hard to implement feature?

**Comment by chros73** [comment]
This can be closed: the fix is merged. https://github.com/rakshasa/rtorrent/pull/446
