### ISSUE TITLE
rtorrent prevents harddisk spin down

### ISSUE THREAD

**Issue by skydreamer888** [rakshasa/rtorrent#340]
It seems rtorrent access harddisk every 20 min, even all tasks are complete or all tasks are removed.

Is there any option to stop this behaviour?

**Comment by chros73** [comment]
Here is a good explanation and fix for this from ituser694: https://github.com/rakshasa/rtorrent/issues/180#issuecomment-55140832

**Comment by skydreamer888** [comment]
But I think increase the time interval between session save causes problem when rtorrent restart.

It is not possible to stop this schedule when all tasks are complete or all tasks are removed?

**Comment by chros73** [comment]
1. about restarting the client:
Do you restart it every day? :) Long session saving interval (e.g. 1 day) can cause problems only in couple of occasions: crashed rtorrent or unavailable remote tracker service, since rtorrent reports usage per torrent to trackers based on their refresh interval.
If you restart it manually you can fire up this command manually before restarting in the main view (key 1), it will save session data for all the torrents: 
`d.multicall=,d.save_full_session=`

2. "t there some test or internal variable can indicate no active tasks and schedule command executes conditionally"
Probably you can mimic this behaviour via config file commands but it's not so easy to do that.

**Comment by pyroscope** [comment]
`session.save` is a built-in, btw. No need for an explicit multicall.

**Comment by chros73** [comment]
"session.save" I forgot about it.
And this is an interesting idea, indeed! Thanks
