### ISSUE TITLE
clarify syntax for moving completed .torrent after download completes

### ISSUE THREAD

**Issue by mrsmileyforprez** [rakshasa/rtorrent#385]
Hello,

What I'm trying to accomplish is for rtorrent to move just the completed .torrent file from a watched directory (using the `mv` command) only **after** the download has completed; if this isn't possible, deleting/removing the .torrent is OK too.

~~The line in my config file I'm trying to do this with is: `method.set_key = event.download.finished,"execute2=mv,-n,$d.loaded_file,/done/"`~~

I've spent a bit of time reading through the internets and github, but I can't figure out what I'm missing; I'm using rTorrent 0.9.2/libtorrent 0.13.2 and I've updated all of the commands in my startup script to the new formats, but I still can't get rtorrent to move/delete a .torrent using the `execute2` command with `event.download.finished`.I'm using rtorrent on OSX, having built it from the source in Macports.

I don't get any errors in rtorrent, and the client runs fine...just doesn't move/delete any .torrents :(

I've pasted in my .rc config file - thanks in advance if anyone can point out where I've made an error, hopefully it's a simple one!

[rt.rc.txt](https://github.com/rakshasa/rtorrent/files/109067/rt.rc.txt)

EDIT AND UPDATE:

I've kept pecking away at my problem, and found [https://github.com/rakshasa/rtorrent/issues/358](url), which pointed me  [here](https://github.com/chros73/rtorrent-ps/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L76), which gave me a better look at the correct syntax for my config file. I just want to move the meta files, so I hacked together some of the script into this:

[new-config.txt](https://github.com/rakshasa/rtorrent/files/109281/new-config.txt)

Everything looked good, but I kept getting `Event 'event.download.hash_done' failed: Bad return code.` errors in the rtorrent log when using this solution. (╯°□°)╯︵ ┻━┻ I couldn't figure out how to clear them, so next best thing (and it works!):

`#makes a copy of the original .torrent to "/finally/`

`method.set_key = event.download.inserted_new, copy_orig_torrent1, "execute={cp,--,\"$cat=$d.tied_to_file=\",/finally/}"`

`#sets up the deal that will rm to delete the original .torrent file`

`method.insert  = d.del_tor, simple, "execute={rm,-f,\"$cat=$d.tied_to_file=\"}"`

`#when the hash event occurs, rtorrent makes sure that if the download is complete,  then it'll run "d.del_tor"`

`method.set_key = event.download.hash_done, del_orig_tor, "branch=d.complete=,d.del_tor="`

So, success ^_^ Thanks to everyone who contributes will suggestions here for rtorrent, and to rakshasa and others who contribute to the code o7

**Comment by mrsmileyforprez** [comment]
Got it fixed - hacked together a copy and delete .torrent file, rather than a move .torrent on completion.

**Comment by pyroscope** [comment]
BTW, the proper way to delete the tied-to file is d.delete_tied

**Comment by chros73** [comment]
There are couple of problems with your rewrite in new-config.txt :
1. you still use `$d.custom=meta_dir` variables while you don't have it in your config, you have `$meta_dir=` instead . (The original script has defined them in this line: https://github.com/chros73/rtorrent-ps/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L90)
So, just change them to `$meta_dir=` and it will work.
2. you don't need these lines since you don't use it:
- `method.insert  = d.compare_meta_path, simple|private, "not=\"$equal={d.get_meta_path=,d.tied_to_file=}\""`
- `method.insert = data_dir,  string|const|private, "$cat=/the.stuff/"`

**Comment by mrsmileyforprez** [comment]
Hi pyroscope and chros73,

Thanks for the tip about d.delete_tied and meta_dir, I've made the changes to my config and deleted the unneeded lines.

You guys are pretty active here helping out and responding to questions - thanks again for the help :)

**Comment by chros73** [comment]
:) You're welcome and thanks for the kind words!
Pyroscope is the real master, apart from rakshasa, I learned a lot from these guys. :)

**Comment by nevvermindme** [comment]
Since my problem is somehow related to this already closed issue I hope nobody minds if I resurect this and not create a new issue.

I'm trying to achieve what mrsmileyforprez wanted to. Move my .torrent files into a folder after download completes and link that new location in rtorrent (using  rTorrent 0.9.6/0.13.6 or archlinux).

This is what I have:

```
method.insert = cfg.dir.torr.copy, string|const|private, (cat,"/torrents/")

# insert a method to determine just the basename of a given meta (.torrent) file
method.insert  = d.get_meta_basename, simple|string|private, "execute.capture=sh,-c,\"echo -n \$(basename \\\"$1\\\")\",getMetaBasename,$d.tied_to_file="

# insert a method which returns the fullpath of its final meta dir
method.insert  = d.get_meta_path, simple|string|private, "cat=$cfg.dir.torr.copy=,$d.get_meta_basename="

# insert a method which: moves meta (.torrent) file to its final place; updates the tied meta file path of the torrent (to keep seeding it)
method.insert  = d.move_meta, simple, "execute2=mv,-f,$d.get_tied_to_file=,$d.get_meta_path=;d.tied_to_file.set=$d.get_meta_path="

# finally, set a key with the name 'move_it' that is triggered by the finished event: moves meta (.torrent) file when it's finished
method.set_key = event.download.finished, move_it, "d.move_meta="
```

So my torrents actually get copied in the /torrents/ directory and rtorrent d.tied_to_file= gets properly updated.
The problem is when the .torrent filename contains spaces. Somehow the filename at the destination has quotes around the filename, which is a problem because it doesn't match the path in rtorrent.
I've been downloading small torrent files to test and tweak my config but I can't seem to figure out what the problem is.

example contents of /torrents/:

```
'Alan Watts - WHAT IS ZEN [2000].torrent'
'Carl Jung - Psychological Types [1921].torrent'
'James Blunt - 1973 [PDF].torrent'
'Ken Follett - Capătul veșniciei.pdf.torrent'
Lennar.Digital.Sylenth1.Soundbank-NoGRP.torrent
'Philip Roth - Nemesis [2010].torrent'
```

The exec log looks ok, so I'm not sure exactly what adds those quotes around the name, I would imaigine it may not be a rtorrent issue since the 'mv' command looks ok...
log.execute= example output:

```
---
mv -f //home/torrent_user/Autoload_me/Carl Jung - Psychological Types [1921].torrent /torrents/Carl Jung - Psychological Types [1921].torrent
---

--- Success ---

---
sh -c echo -n $(basename "$1") getMetaBasename //home/torrent_user/Autoload_me/Carl Jung - Psychological Types [1921].torrent
---
Captured output:
Carl Jung - Psychological Types [1921].torrent
--- Success ---
```

P.S. There is another issue though, that I find odd. That extra slash (/) in front of the path. I can see that in new torrent files in 'rtorrent->select torrent->info-> Tied to file:' section as well.

**Comment by chros73** [comment]
Interesting, I don't have any issue like this  during moving meta files, and loads of them contain spaces.
My system is Ubuntu 14.04 x64, ext4 filesystem.
So you say that the problematic filenames include surrounding `'`s ? That's freaking strange, and I don't think at all that it's rtorrent fault, but who knows? :)

Here's my current [related code block](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L98) that works (containing more checks), although I don't see any major changes compared to yours.
What happens if you remove `|string` definition from those two methods that uses `simple|string|private`, to be like this: `simple|private`?

About the double `//` at the beginning: it's a known rtorrent issue, not a biggie, but @pyroscope has already created a [pull req](https://github.com/rakshasa/rtorrent/pull/583) for it, that is already in place in `rtorrent-ps` or in `rtorrent-ps-ch`.

**Comment by kannibalox** [comment]
You're quoting `$1` properly, but not the `$()`. Also, you can just pass in `$d.tied_to_file=` as the 0th argument and use `$0` if you want.

**Comment by pyroscope** [comment]
What you do wrong is to not minimize code in RC hell. Let a script do the mv and path wrangling, pass in all the vars, echo and capture the target path, set that as the new tied file.

**Comment by nevvermindme** [comment]
Thanks all for such a quick answer, glad to see the project is so active. So unfortunately I had/have very little time to further test your suggestions this week, but I decided to switch to rtorrent-ps + pyroscope anyway, especially for the ability to take automated actions based on tracker name.
That's what I'm doing currently with deluge, which started to show it's limitations with lots of meta files, and which also pales in comparison with what I managed to read about ps+pyro.

I just need to RTFM and put it together, I imagine the issue above will become nonexistent with scripts.

One question though: did you guys test (estimate) any potential resources overhead (RAM/CPU) required that the user interface improvements and features  in rtorrent-ps bring on top of the original rtorrent? I imagine not much (insignificant), but the reason I didn't jump on rtorrent-ps directly is that my setup is running on a raspberry pi with additional services running besides rtorrent/rutorrent. Though I'm fairly certain it will be less than the deluge daemon, I will probably need to run them side by side until I finish the transfer (gonna do it in stages so I apply tweaks in settings/scripts) and I want to keep the system as efficient as possible.

Keep up the awesome work!
