### ISSUE TITLE
torrent filename bug?

### ISSUE THREAD

**Issue by rezad1393** [rakshasa/rtorrent#391]
I have downloaded a torrent file with another torrent client and now I want to seed it in rtorrent.
but when I add the file to rtorrent the filename has a character that cant be correctly shown in rtorrent and on the download folder the file name is also wrong.
what can I do to fix this?

this is the filename

Peccati di gioventù (Silvio Amadio)(Eng) -1975- Ce.avi

and this is the file that rtorrent creates

Peccati di giovent� (Silvio Amadio)(Eng) -1975- Ce.avi

**Comment by pyroscope** [comment]
This is an error in your overall configuration, both rTorrent (encoding.add) and the shell environment (LANG). Or put another way: it works if you make it work.

**Comment by rezad1393** [comment]
and maybe helping me fix it by pointing to something more specific would help too?

**Comment by rakshasa** [comment]
RTorrent should probably move to only doing UTF-8 as the issues surrounding locale-specific filenames and such is too much of a hassle.

Anything that does not support UTF-8 might as well be ignored, as that is really the only thing we need.

**Comment by Yogi1** [comment]
I'm having the same type of problem with diacritics. Could someone please be so courteous and explain a bit more about it. Is there a way to fix / circumvent that problem or not?

Very interesting to note that on my Mageia Linux system for a given torrent metainfo file (.torrent), rTorrent (and ruTorrent of course) are showing me _ or ? whereas uTorrent 2.0.4 on Wine is showing the proper character. My guess: the cause must be that I created the .torrent file with uT 2.x which probably was not supporting / using UTF-8 encoding. Does that make sense? In any case, I tried all the ways to have rTorrent at least create the file name (with any garbage char) but could simply never succeed. Made me half nuts!

**Comment by pyroscope** [comment]
There is neither an easy explanation nor an easy cure (sync tools have extra code to fix the mess, sometimes), since the combo of app, file system and OS + their configuration determines what works and what not. And we didn't even talk about Unicode normalization, of which there are different methods… :grimacing:

**Comment by Yogi1** [comment]
Not sure exactly about what you mean with "sync tools" but I realised after having written my post above, that actually I created the .torrent with mktorrent originally (on WinXP). How can that be working with wine on Linux but not natively? I spent enough time checking my system locales and that seems to be good (UTF-8). Could be that wine is somehow translating the "non UTF-8" to UTF-8. About the FS: I did several tests with different file systems (NTFS, BTRFS) and the results where always negative. Looks to me the problem is not solvable. :/ Still I really wonder what is the core of the problem in this specific case?

Of course all that would not be a big problem, if it would be possible to relocate or rename files within r/ruTorrent. I'm surprised nobody asked for such a feature (seems so at least).
