### ISSUE TITLE
rtorrent 0.9.6 - max_downloads_global don't work

### ISSUE THREAD

**Issue by barchan** [rakshasa/rtorrent#397]
I set "max_downloads_global = 2" but rtorrent anyway downloading all added torrents...
please help!

**Comment by chros73** [comment]
Because `max_downloads_global` isn't for this, but it means: maximum number of simultaneous download slots (you can see it right of the status row: [D x/2]).
There's a setting called `scheduler.max_active.set` that supposed to limit the global active torrents in the client but it doesn't just limit downloading but uploading as well, and it worked pretty 'interesting', so I couldn't use it.
What you need is to implement some sort of queue support:
- pyroscope did it in rtorrent-ps https://github.com/pyroscope/rtorrent-ps and pyrocore https://github.com/pyroscope/pyrocore
- although I'm using both from pyroscope, but I have implemented my own solution https://github.com/chros73/rtorrent-ps (I haven't pushed the helper script, since nobody was interested in it :) )

**Comment by barchan** [comment]
chros73: sir, thank you for help, I will try this method.

**Comment by pyroscope** [comment]
Solved. This should be closed.

**Comment by SMooxx** [comment]
any rutorrent plugins for this function? need this feature desperately.

**Comment by kannibalox** [comment]
You'd be better off asking in ruTorrent's repo: https://github.com/Novik/ruTorrent, but I don't believe there are any queuing plugins in the main repo.
