### ISSUE TITLE
Tracker Information Not Updating Peers/Seeds/Last Updated.

### ISSUE THREAD

**Issue by scoobynz** [rakshasa/rtorrent#413]
Hello,

This was initially discussed here;
[https://github.com/rakshasa/rtorrent/issues/386](url)

This is with rtorrent 0.9.6/0.13.6 on debian. It only happens with specific trackers, perhaps only those that send a min interval which rtorrent selects? 

The announce seems to happen but the tracker information is not synced into rtorrent. I can demonstrate below;
The tracker information from the site;
![capture](https://cloud.githubusercontent.com/assets/1527999/14059609/500a1b1a-f381-11e5-8acb-2ebff19d0032.PNG)
The tracker information in both rtorrent and rutorrent, note that they are in sync and rutorrent has a long period since last update;
![capture2](https://cloud.githubusercontent.com/assets/1527999/14059613/67b28eaa-f381-11e5-8e60-7c5da33d2086.PNG)
![capturexx](https://cloud.githubusercontent.com/assets/1527999/14059631/06df25a6-f382-11e5-890a-f8134fae505e.PNG)

Lastly, here is the information from the log for the announce;
![announce](https://cloud.githubusercontent.com/assets/1527999/14059623/abe07d58-f381-11e5-8d92-9fdb1e2ddf02.PNG)

Assistance and comments appreciated. At present it appears that rtorrent isnt updating tracker information for some sites.

**Comment by scoobynz** [comment]
OK. As an update on this, I downloaded and installed the standalone version of rtorrent-PS, 0.9.4 for debian Wheezy. I installed this by the .deb file on my system. I trialed a torrent file and get the exact same behavior as above.

Trying to zone in on the issue then. Does the installed ,.deb of rtorrent-PS use the version of xmlrpc-c that I compiled when installing the standalone version of 0.9.6 on my system?

**Comment by pyroscope** [comment]
`ldd /opt/rtorrent/bin/rtorrent `

**Comment by scoobynz** [comment]
Of course! drrr. This shows the rtorrent-PS uses its own standalone version of xmlprc, libcurl and libtorrent. Will keep thinking what else it may be then.

**Comment by chros73** [comment]
I found out how it works: I just restarted rtorrent 2 days ago and I noticed that it updated this info! After that I checked what happens at startup and it fires this request for every torrent (even stopped one) only once (with a 30 sec delay): https://github.com/rakshasa/rtorrent/blob/9abcea84c7f7594ef9cc99f151467cf8b718a9c0/src/main.cc#L265

First of all, it "just" a cosmetic issue, it won't affect how rtorrent works at all. Other clients use this info to manage their auto queuing feature (rtorrent behaves differently by default).

Solution:
1. You can try out the update with this command (after pressing CTRL+X):
```d.multicall2=main,d.tracker.send_scrape=0```

2. The easy fix would be adding something like this into our rtorrent config (to fire it up in every 3 hours for all the torrents):
```schedule = last_scrape_s, 10830, 10800, "d.multicall2=main,d.tracker.send_scrape=0"```

3. Instead of this I implemented a better solution: https://github.com/chros73/rtorrent-ps_setup/commit/d16ffc5c11c6e76fc0b3a03649d17b9f2d09897d

I've also updated the corresponding wiki page: https://github.com/rakshasa/rtorrent/wiki/User-Guide#the-tracker-list-screen

Enjoy!

**Comment by scoobynz** [comment]
Thanks chros73! I too had come to the conclusion also that this was a cosmetic issue only, rtorrent was obviously finding new peers and uploading etc even if it wasnt showing this in these columns. I added the line;
`schedule = last_scrape_s, 10830, 10800, "d.multicall2=main,d.tracker.send_scrape=0"`
into my .rtorrent.rc problem and now I am getting some updates, which is good enough for me at present.

Thanks for getting some resolution and clarification on this. Not sure if this is something that can be fixed in the base code in time or not?

**Comment by chros73** [comment]
I'm pretty sure it won't happen any time soon (and probably never): multiscraping isn't even implemented in libtorrent (and it's not a 1 hour job to do).
So, currently if you use the one liner above that mean rtorrent fires up all the requests at the same time: if you have 2000 torrents that means 2000 requests. :)

So I suggest to use something similar to this (you can just copy paste that block): https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L236
(And you can close this issue.)

**Comment by scoobynz** [comment]
Thanks. Updated my .rtorrent.rc with the suggested block and all working OK. Thanks for your assistance with this.
