### ISSUE TITLE
The fault address is not part of any chunk

### ISSUE THREAD

**Issue by MosEisley34** [rakshasa/rtorrent#417]
I'm running rTorrent 0.9.6 with libtorrent 0.13.6 on Ubuntu 15.04 server. I've suddenly started getting this error immediately after starting rTorrent:

Caught SIGBUS, dumping stack: 2.1/  2.6 KB] [Port: 55985] [U 1/0] [D 0/0] [H 32/32] [S 399
rtorrent() [0x41328e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10d10) [0x7fd5ebc68d10]
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0(+0x6a618) [0x7fd5ea434618]

Error: Success
Signal code '2': Non-existent physical address.
Fault address: 0x7fd5d482d000
The fault address is not part of any chunk.

I figured this was an error caused by a faulted hard disk drive so I ran a HDD repair tool included in Hiren's Boot CD, this fixed 77 bad sectors on the drive. But, when I restarted my server I keep getting this error. Is there any known fix?

**Comment by apendragon** [comment]
I encounter this error when the filesystem where my download directories are stored is full. Just free space or increase its size solves this error on my side.

**Comment by dbedrenko** [comment]
This is still a bug, because the behaviour should be that rtorrent puts all leeching torrents in stop state rather than crashes.

Also, it seems rtorrent doesn't respect this config line:
```
schedule = low_diskspace,5,60,close_low_diskspace=500M
```
because my filesystem ends up having precisely 0 free space upon crash. Maybe the crash caused is due to this fact?
