### ISSUE TITLE
Sorting the started view causes announces to fire

### ISSUE THREAD

**Issue by Speeddymon** [rakshasa/rtorrent#449]
Ref: #386 

Sorting the started view, such as on a schedule, causes the announces for all started torrents to fire.

This can lead to announces being sent to trackers every second, in some schedules, which can lead to being banned from some trackers, or at the very least, a warning from the administrators about hammering the tracker.

The suspected cause is that the torrents are all removed from the started view, and then added back in the specified order, which causes the state of the torrents to change from 1 to 0 to 1 again, and that all runs through the following line of code:

https://github.com/rakshasa/rtorrent/blob/efc9097d62cd93e2d139d6d321b5a71d1b169502/src/main.cc#L310

The state change is likely what is causing the announce itself to be sent, however the sorting of the view should ideally not trigger a state change, except that right now it does.

**Comment by Speeddymon** [comment]
Hi,

I have some additional information to add which is sensitive in nature. Please provide me details on how I can provide this additional information privately to one of the developers.

**Comment by chros73** [comment]
On second thought, I'm not sure whether the state change is responsible for this (those are events).
I'd vote for the `scheduler.simple.added` event. 
Can you try out with `stopped` view? This doesn't include the above event. I'd be curious if we reproduce the problem or not.

Thanks

**Comment by Speeddymon** [comment]
I have a sort for the stopped view also. It doesn't cause this, however I figured that was due to the stopped torrents not being announced to the trackers.

Still need to relay some info to you privately somehow, for what it's worth.

**Comment by chros73** [comment]
Thanks for the feedback: I edited the post above in the meantime (sorry, I haven't noticed that you've already answered).

**Comment by Speeddymon** [comment]
Ok let me try your modified config and see if the other bug is present with it also.

**Comment by Speeddymon** [comment]
```
view.sort_current=started,less=d.name=
view.sort_new=started,less=d.name=
view.sort=started
view.event_added = started,{(d.state.set,1),(scheduler.simple.added)}
view.event_removed = started,{(view.set_visible,stopped),(scheduler.simple.removed)}
schedule2=sort_started,10,10,view.sort=started
```

Unfortunately the above causes all torrents to stop every time I try to start them.

(Note: Since my OP, I went through and updated all commands in the config file to the 0.9.6 way of doing them)

**Comment by chros73** [comment]
Yes, I noticed that.
I did dig into the source code and I think I've found the problem and but my fix doesn't work.
But first:

1. It seems that these 2 views (`started` and `stopped`) are special https://github.com/rakshasa/rtorrent/blob/master/src/main.cc#L308
They are like some entry points for managing torrents. That's kind of weird to handle something like this in a view. 
That means we can't modify the logic defined there (because I don't know how it works :) ).

2. The problem is (I think): actually not scheduling `view.sort` but `view.filter` !
Add only this to your working config and we recreated the bug: 
`schedule2 = filter_started,12,10,"view.filter = started, not=$d.complete="`
Because `view.sort` doesn't include anything special https://github.com/rakshasa/rtorrent/blob/master/src/core/view.cc#L248 , but below it `view.filter` does (!): it deals with the defined event commands in main.cc https://github.com/rakshasa/rtorrent/blob/master/src/main.cc#L308
Though `view.sort` using `filter` first: https://github.com/rakshasa/rtorrent/blob/master/src/core/view_manager.cc#L92 , and that's our problem (I think).

3. Quick dirty solution would be: do not allow `filtering` for `started` and `stopped` views inside `view.sort`. But this patch does NOT WORK for some reason (the bug is still there).
See this patch (will be fine with 0.9.6 and current master as well): https://github.com/chros73/rtorrent-ps/commit/69048deeab95b3e5a6c741b666916371b2a652e4
And here's the branch for it in patched rtorrent-ps (if you want to try it out): https://github.com/chros73/rtorrent-ps/tree/fix_sort_started
After compiling and trying it out we shouldn't see any weird problem with scheduling `view.sort` on `started` and `stopped` views with: 
`schedule2 = sort_started,12,20,((view.sort,started))`
But I do see the problem! :)
(This would mean (if it have worked) that we sacrifice scheduled filtering capability (via sorting) for sorting capability. But I don't think that it's an issue for now, since they aren't filtered by default anyway.)

@rakshasa Any idea about this? Thanks

**Comment by chros73** [comment]
The logic does work (I made a silly bug in the condition, now it's fixed). I've updated the post above.
I don't experience the issue on my test setup with this patch: https://github.com/chros73/rtorrent-ps/blob/fix_sort_started/patches/ps-fix-sort-started-stopped-views_all.patch

To be clear, with this patch:
- we CAN use scheduled `view.sort` command on these views: `started` , `stopped`
- we are still NOT allowed to use `view.filter` command on these views: `started` , `stopped`

The latter has to be mentioned later on the wiki under Issues: https://github.com/rakshasa/rtorrent/wiki/Issues (I just linked this issue for now.)

@Speeddymon Can you try it out? And thanks for mentioning this and for contributing to the wiki as well!

@rakshasa If you agree with the logic above and you'll accept this dirty fix then I will create a pull request.

**Comment by chros73** [comment]
Patch2 (instead of the previous one): https://github.com/chros73/rtorrent-ps/blob/fix_filter_started/patches/ps-fix-sort-started-stopped-views_all.patch
branch: https://github.com/chros73/rtorrent-ps/tree/fix_filter_started
- since `view.filter` causes problem not `view.sort`, don't allow to use `view.filter` with `started` and `stopped` views.

It works better then the previous one:
- no issue either
- it ignores scheduled filtering like this: `schedule2 = filter_started,12,10,"view.filter = started, not=$d.complete="` , so the bug won't be triggered by accident.

(I've searched through the source code and it shouldn't break anything.)

@Speeddymon Can you try out this patch2 (that patches `view.cc`)? 
It works for me, e.g. with this rtorrent-ps config:

```
# started view
schedule2 = filter_started,12,10,"view.filter = started, not=$d.complete="
branch=pyro.extended=,"view.collapsed.toggle=started"
branch=pyro.extended=,"view.sort_current = started,\"compare=+-,d.complete=,d.last_active=\"","view.sort_current = started,greater=d.last_active="
schedule2 = sort_started,12,10,((view.sort,started))

# stopped view
schedule2 = filter_stopped,12,10,"view.filter = stopped, d.complete="
branch=pyro.extended=,"view.collapsed.toggle=stopped"
branch=pyro.extended=,"view.sort_current = stopped,\"compare=++-,d.complete=,d.throttle_name=,d.custom=tm_loaded\"","view.sort_current = stopped,greater=d.custom=tm_loaded"
schedule2 = sort_stopped,12,10,((view.sort,stopped))
```

**Comment by Speeddymon** [comment]
Hi @chros73 

Seems my last comment didn't get posted.

I can't compile on this machine as its not my machine to muck around with, even though I have root.

However, if @rakshasa accepts the fix, I can get the distro maintainers to port the fix to their build and I can yum update rtorrent with the new patch.

I'm hopeful it will also fix another bug I need to report privately but haven't yet been able to figure out how to do so.

**Comment by chros73** [comment]
Ok, no problem. But it won't happen soon, I think :)

**Comment by Speeddymon** [comment]
That's fine for me. The sorting is not a big issue so much since I mainly watch the Active view. :-) But, eventually will be nice to have for started view. :-) Thanks again for your help with diagnosing this.

**Comment by chros73** [comment]
And fixing it :) Yw.
Btw, have you used rtorrent-ps?

**Comment by Speeddymon** [comment]
And fixing it. Yes. :-)

No, I'm afraid not since I don't own the server.

**Comment by chros73** [comment]
I've added and commented the pull request.

(About rtorrent-ps: try to convince them or you can compile it into your home dir. It will open up a whole new world! :) )

**Comment by Speeddymon** [comment]
Looks like pull requests are not working even for non-code changes. I just tried to do a pull request to updated the example rtorrent.rc in the docs folder, and got the same compile errors. @rakshasa will need to open a support case with GitHub to resolve that.

**Comment by Speeddymon** [comment]
I have reported this downstream with Fedora, in the hopes that they will include the fix in their build, in spite of a lack of a response from @rakshasa 

https://bugzilla.redhat.com/show_bug.cgi?id=1354125
