### ISSUE TITLE
session.path.set do not work with rtorrentInitScreen.sh

### ISSUE THREAD

**Issue by barchan** [rakshasa/rtorrent#567]
Hello! I use rTorrent 0.9.6, when I try use `session.path.set` with rtorrentInitScreen.sh i got error: 
`#service rtorrent start`
`cannot find readable session directory  from config /root/.rtorrent.rc. check permissions`

when i changed `session.path.set = ` to `session = ` everything work fine.
i am launch rtorrent from root user. where i am wrong? thank you!

**Comment by chros73** [comment]
You're right, it's a bug in the script [here](https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/init/rtorrentInitScreen.sh#L107). Possible solutions:
- use `session =` in config
- or modify the above line to set the full path manually in the script (see below why)

The bigger "problem" is that you can use variables to set session dir, like you see it in the [config template](https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template#the-template) example. With that approach there's no clear way to determine what the session dir is set to.

One more thing: use tmux instead of screen if you can do it. :)
