### ISSUE TITLE
Perfect piece size for 500 GB big torrents?

### ISSUE THREAD

**Issue by xbtowbw** [rakshasa/rtorrent#574]
We have a seedbox with like 5000 big torrents. We have 2 kinds of torrents:

1. 1-3 GB with 500M - 2.5 GB files inside
2. 100 - 500 GB with 5 - 25 GB files inside

Usually up to 40 of the 5000 torrents are active. We are trying to optimize performance of the seedbox.

QUESTION: What would in your experience be the perfect PIECE SIZE to choose when creating these torrents?

**Comment by chros73** [comment]
I'm not sure that it would make any difference at this point.
Take a look at this issue #443 I'm curious about your result.

**Comment by pyroscope** [comment]
How is #443 even related? The optimal piece size is the one a computer calculates for you, using a non-braindead tool.

**Comment by xbtowbw** [comment]
And what would this non-braindead tool be? Where do I find it?

**Comment by pyroscope** [comment]
https://pyrocore.readthedocs.io/en/latest/references.html#cli-usage-mktor

Of course I'm totally unbiased. ;)

**Comment by xbtowbw** [comment]
We checked the code of your mktor @pyroscope :-)

     piece_size_exp = int(math.log(total_size) / math.log(2)) - 9
               piece_size_exp = min(max(15, piece_size_exp), 24)
               piece_size = 2 ** piece_size_exp

Is there a reason 16MB is the maximum piece size you create? What about bigger pieces?

**Comment by pyroscope** [comment]
Bigger is outside the spec / what many clients in the wild can manage.

**Comment by xbtowbw** [comment]
What can rtorrent handle?

**Comment by rakshasa** [comment]
Only limitation is IIRC a sanity check when loading a torrent, don't remember what it was set to.

**Comment by chros73** [comment]
> How is #443 even related?

You were right, it isn't. I thought it was a combination of upload slots and chunk sizes.

**Comment by ruthtern** [comment]
Apologies for reviving an old thread 
Personal preference - calculate piece size so that there are between 512 and 1023 pieces 
The arithmetic requires a base2 log calculation 
The 16MB maximum some people use is a limit imposed by one client in particular, the 2.2.1 version (and earlier versions) of uTorrent, which are really popular even though they are years out of date 
Apart from uTorrent 2.2.1, it should be OK to use piece size at least up to 256 MB. The largest I have used is 64MB, worked perfectly with Transmission 2.92 at both ends, for 220GB total file size
