### ISSUE TITLE
Help - Move Downloaded

### ISSUE THREAD

**Issue by veganexe** [rakshasa/rtorrent#654]
I use the following .rtorrent.rc
```

scgi_port = localhost:5000

schedule2 = watch_directory_uploads, 10, 10, "load.start_verbose=/var/sftp/uploads/*.torrent,d.set_custom1=/var/www/html/Downloads"

system.method.insert=checkdirs1,simple,"not=\"$equal={d.get_custom1=,d.get_base_path=}\""

system.method.insert=movecheck1,simple,"and={checkdirs1=,d.get_complete=,d.get_custom1=}"

system.method.insert=movedir1,simple,"d.set_directory=$d.get_custom1=;execute=mv,-u,$d.get_base_path=,$d.get_custom1=;d.set_custom1=;d.stop=;d.start="

system.method.set_key=event.download.hash_done,move_hashed1,"branch={$movecheck1=,movedir1=}"
```

I have to manually check the hashes or restart rtorrent to move the data.
And I want all torrents to follow this. Not just the watch folder.

Please help

**Comment by veganexe** [comment]
Please give some pointers atleast :(

**Comment by chros73** [comment]
It looks good though. Which version are you running?

Comments:
- use new syntax (0.9.x):
  - e.g. instead of `d.get_custom1=`, `d.custom1=` ; `d.get_base_path=`, `d.base_path=` etc.
  - use `d.directory.set` instead of `d.set_directory`
  - use `method.insert` instead of `system.method.insert`
- you can't trust in `d.base_path=`, here's a [workaround](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#getting-the-full-path-of-data-of-a-torrent) for it
- `movedir1` method looks good:
  - isn't `-f` flag (force) is better than `-u` for `mv`
- you can "debug" your script if you put (or manually fire it up at CTRL+X):
  - `print=true` or `print=$d.custom1=`

> I have to manually check the hashes or restart rtorrent to move the data.

That means the hash event doesn't get fired up for some reason:
- how the data and the torrent file gets into there places?
  - if it's configured properly then the data should be already there and when you ftp a torrent file into the watch dir then hashing should start straight away

> I want all torrents to follow this. Not just the watch folder

I don't understand this part:
- how other downloads can get into client if not via watch dir?

**Comment by chros73** [comment]
> That means the hash event doesn't get fired up for some reason:
Oh, if you set this in your config, then hash checking only occure if you already have the data and drop a torrent file into your watch dir (as I implied above) and **not** when you download something.
```
# Check hash for finished torrents. (check_hash)
pieces.hash.on_completion.set = no
```

You have to use 1 more `event.download.finished` for the latter case.

PS: if you like the idea of moving data around take a look at [this setup](https://github.com/chros73/rtorrent-ps-ch_setup), maybe it will suit you as well.

**Comment by veganexe** [comment]
Thanks.i was using a config meant for an older version.

My config is now this and it's working to some extent : 

```
scgi_port = localhost:5000

directory = /root/Downloads/

schedule2 = watch_directory_uploads, 10, 10, "load.start_verbose=/var/sftp/uploads/*.torrent,d.set_custom1=/var/www/html/Downloads"

method.insert = d.get_finished_dir, simple, "cat=,$d.custom1="

method.insert = d.get_data_full_path, simple, "branch=((d.is_multi_file)),((cat,(d.directory))),((cat,(d.directory),/,(d.name)))"

method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="

method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.get_data_full_path=,$d.get_finished_dir="
```

But there are some issues

- If rtorrent is restarted the torrents are downloaded again.

- If torrents are added through the GUI (in Flood), after they download they move to the wrong location. 
That is, if I just add without a 'tag' (download path) it moves to "./somefile".
And if I set the tag as the download location while adding. It moves to "%var%www%html" (something like that.

**Comment by chros73** [comment]
Notes:
- `"cat=,$d.custom1="` is the coding old style, so you don't need `,` (it's a parameter separator) : `"cat=$d.custom1="` 
- you don't need this `execute=mkdir,-p,$argument.1=;` in `d.move_to_complete` (of course you can use it)
  - and you need to stop and start the download in the end of the method (as you had it in the 1st example)
- I think a similar check is also needed that you used in your 1st example (`movecheck1`)
  - "If rtorrent is restarted the torrents are downloaded again."
- and you also need `event.download.hash_done` if you want to support dropped in data

Here's a [massive config](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc) that can you give hints how things can be done with scripting.

> If torrents are added through the GUI (in Flood), ...

I never used it. My best guess that it doesn't use your `d.custom1` property at all.
You have to ask the Flood devs about it.
