### ISSUE TITLE
Suggestion: clear completed keystroke

### ISSUE THREAD

**Issue by vonpupp** [rakshasa/rtorrent#669]
Hi,

Thanks for rtorrent, it is just great! If you don't mind I would like to suggest a feature, it would be nice to have a keystroke combination to clear all the fully downloaded torrents from the list.

Best regards.

**Comment by pyroscope** [comment]
There is no "the" list. Just use the incomplete view.

**Comment by vonpupp** [comment]
Thanks @pyroscope. I think I got your point, however my suggestion is not oriented on filtering the list, but rather removing the completed from it.

Let me try to elaborate on this. I download torrents on a raspberry pi which is limited in space. Once downloaded I move the completed files using rsync to a bigger storage, however I have noticed that when I close rtorrent and open it again it sometimes download again the whole torrent. Sometimes it seems to get stuck on "open" status. This is why I suggested this.

**Comment by chros73** [comment]
> ... I would like to suggest a feature, it would be nice to have a keystroke combination to ...

These kind of features won't ever be implemented. Not because they aren't useful but there are so many possibilities.

But the good news is: they don't have to, since @pyroscope implemented generic [keyboard shortcut assignement](https://github.com/pyroscope/rtorrent-ps/blob/master/docs/manual.rst#ui-bind-key-display-key-command1) to various commands in [rtorrent-ps](https://github.com/pyroscope/rtorrent-ps) .

So, you need some other commands as well to achieve what you want on the `completed` view: `d.multicall2`, `d.erase`, etc.

**Comment by pyroscope** [comment]
Actually https://pyrocore.readthedocs.io/en/latest/usage.html#automatic-stop-of-items-having-problems – why have a key when you have cron?

**Comment by vonpupp** [comment]
Thank you guys.

I haven't used pyrocore yet but I will give it a try =)

I am closing the issue and if necessary I will post here again.

**Comment by chros73** [comment]
> why have a key when you have cron?

It's even simpler solution!
