### ISSUE TITLE
[Question] Retrieve torrents field in bash ?

### ISSUE THREAD

**Issue by Jedediah04** [rakshasa/rtorrent#691]
Hello guys :-)

I'm using rtorrent on a server at home. The rtorrent service is binded on the tun0 interface of my VPN so my public IP is not used by torrents.
I use some "special" torrents that check my "torrent IP" so I'm sure that my public IP is not leaking on trackers I use. This information is shown in the status of those special torrents.

I would like to know if there is a way to retrieve this status field in CLI. This way I could make a bash script to send me an email if the ip address in the status field is not from my VPN provider.

Thank you guys ;)

**Comment by chros73** [comment]
Probably you can somehow (others can help you with that), but there's a powerful approach to this problem on Linux:
- you can use network namespaces to completely separate applications/traffic (available in linux kernel since around v3.1x)
  - if you search for it on the net you'll get lot of different solutions, but this is the best: [namespaced-openvpn](https://github.com/slingamn/namespaced-openvpn)

If you need more help with it, just let me know.

**Comment by Jedediah04** [comment]
Hey :)

I'm pretty happy with my solution ATM, everything is working well for a year now.
Only rtorrent is binded (and use) the VPN, everything else is working on eth0 so I don't think it would be necesary to change that.

**Comment by chros73** [comment]
No problem, but believe me, it does: it deals with leakage (and others) :)
Just quickly go through the readme and you'll see what I mean.

**Comment by chros73** [comment]
You can use [rtxmlrpc](https://pyrocore.readthedocs.io/en/latest/advanced.html#using-rtxmlrpc) of [pyrocore](https://github.com/pyroscope/pyrocore) to get back that info in bash.
