### ISSUE TITLE
Make complete view's order persists

### ISSUE THREAD

**Issue by ghost** [rakshasa/rtorrent#711]
Hello,
title says it all, I naively tried `view.persistent = complete`, with an obvious error. Didn't seem to find this in any guide/FAQ and rtorrent's command systemd is pretty confusing to me.

**Comment by pyroscope** [comment]
If you want special views, create new ones instead of mangling the builtin ones.

**Comment by Q3CPMA** [comment]
I was waiting for this kind of answer. Well, I'll try, I guess. Thanks for replying.

**Comment by chros73** [comment]
Is [this](https://github.com/chros73/rtorrent-ps-ch_setup/blob/develop/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L124) that you want? (This setup uses rtorrent-ps, but the 2nd part will work for vanilla rtorrent as well.)

**Comment by Q3CPMA** [comment]
For the COMPLETE view, that's what I wanted, but I want to sort INCOMPLETE by
LAST download activity (to emulate COMPLETED TIME).

Are you sure line 96-161 work in vanilla? The pyro.extended is suspicious to me.

**Comment by chros73** [comment]
> Are you sure line 96-161 work in vanilla?

Probably not in this way, but the 2nd part of the commands will, e.g. instead of the [completed view](https://github.com/chros73/rtorrent-ps-ch_setup/blob/develop/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L124) you can use this:
```
# UI/VIEW: SORT the collapsed COMPLETE view (view #5) by COMPLETED TIME desc
view.sort_new     = complete,greater=d.custom=tm_completed
view.sort_current = complete,greater=d.custom=tm_completed
```

For this to work you need the [custom property definitions](https://github.com/chros73/rtorrent-ps-ch_setup/blob/develop/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L36).

Now you can go through the config to look for ideas and you can try to implement for your need.
But just use rtorrent-ps/rtorrent-ps-ch if you can! :)

**Comment by pyroscope** [comment]
And btw, for incomplete by activity you need the last_xfer custom, because there is no default field for that.

**Comment by Q3CPMA** [comment]
Well, thanks for all of these, the horrible syntax would have been my death
without. I'm tempted to switch to an extended distribution even more now (made
an ebuild for rtorrent-ps some time ago).

But my seedbox uses alpine musl, so I fear stuff won't be easy.

**Comment by chros73** [comment]
> incomplete by activity you need the last_xfer custom

Or `last_active`, although it's slightly different.
But thanks for this as well: I just realised that you have added lot of stuff about a year ago, so now I cherry pick stuff from it before I release my projects.

**Comment by pyroscope** [comment]
Don't forget that lots of it is in p-m-b.

**Comment by chros73** [comment]
Thanks for the reminder, that was I know about and I forgot the pyrocore part :)
