### ISSUE TITLE
Torrents are stopped at the restart

### ISSUE THREAD

**Issue by defhead** [rakshasa/rtorrent#716]
rtorrent version 0.9.2 libtorrent 0.13.2

Since I set up a daily backup of my data, which requires me to stop my docker containers of rtorrent and other stuff and then start them up again, all the torrents that have reached 1 of ratio are stopped and I have to start them myself.

Why is it happening ?

**Comment by kannibalox** [comment]
Use the latest stable version (0.9.6), and please post your config.

**Comment by hbfs-misc** [comment]
hello @kannibalox 
Unfortunately the tracker I use does not allow rtorrent versions above 0.9.2 so I cannot install them.

Here is my config:
<pre>
execute = {sh,-c,rm -f /*********/rpc.socket}
scgi_local = /********/rpc.socket
execute = chmod,ugo=rw,/**********/rpc.socket
encoding_list = UTF-8
port_range = #####-#####
port_random = no
check_hash = no
directory = /*********/data
session = /*********/.session
encryption = allow_incoming, try_outgoing, enable_retry
schedule = watch_directory, 5, 60, "load_start=/*********/watch/*.torrent"
schedule = untied_directory, 5, 60, stop_untied=
schedule = low_diskspace, 5, 120, close_low_diskspace=500M
use_udp_trackers = yes
peer_exchange = no
min_peers = 2
max_peers = 50
min_peers_seed = 2
max_peers_seed = 50
execute = {sh,-c,/usr/bin/php /var/www/rutorrent/php/initplugins.php ************* &}
system.method.set_key = event.download.finished,move_complete,"d.set_directory=\"$cat=/*********/downloads/,$d.get_custom1=\";execute=mv,-u,$d.get_base_path=,\"$cat=/*********/downloads/,$d.get_custom1=\""
system.method.set_key = event.download.erased, remove_file,"execute={rm,-drf,--,$d.get_base_path=}"
</pre>

**Comment by kannibalox** [comment]
Does the issue still occur while rutorrent is turned off? It injects a lot of its own configuration into rtorrent.

Regardless, I'd recommend removing the `untied_directory` line.

**Comment by eleonrk** [comment]
You might be right @kannibalox . I tried several things.

So I noticed that when I comment `execute = {sh,-c,/usr/bin/php /var/www/rutorrent/php/initplugins.php ************* &}` line in my .rtorrent.rc file, the issue disappears.

So I concluded the rutorrent plugins were the problem. I decommented the line and tried to disable them one by one (by moving them elsewhere), and when it came down to "ratio" plugin, the issue was gone.

But I don't understand what could possibly cause that. I use ratio plugin for a long time now and I never had problem. Indeed, recently I switched to docker operating mode, and since then, the issue appeared.

Do you have any ideas?

**Comment by hbfs-misc** [comment]
You might be right @kannibalox . I tried several things.

So I noticed that when I comment `execute = {sh,-c,/usr/bin/php /var/www/rutorrent/php/initplugins.php ************* &}` line in my .rtorrent.rc file, the issue disappears.

So I concluded the rutorrent plugins were the problem. I decommented the line and tried to disable them one by one (by moving them elsewhere), and when it came down to "ratio" plugin, the issue was gone.

But I don't understand what could possibly cause that. I use ratio plugin for a long time now and I never had problem. Indeed, recently I switched to docker operating mode, and since then, the issue appeared.

Do you have any ideas?
