### ISSUE TITLE
ExecFile::execute(...) Fork failed. in LXC container

### ISSUE THREAD

**Issue by Suika** [rakshasa/rtorrent#754]
Found a strange behaviour of rtorrent.

I'm currently running rtorrent in a LXC container on Proxmox distro.
At the beginning rtorrent was running just as expected and was executing external commands normally.
Yet, once I set vm.overcommit_memory to 2 (The Linux kernel will not overcommit memory, and only allocate as much memory as defined in overcommit_ratio.), gave the container 4GB RAM and allowed rtorrent to use 2GB, I started getting ExecFile::execute(...) Fork failed.

I don't know how rtorrent does things, but it seems the system deems any kind of external calls from rotrrent as a overcommit.

**Comment by kannibalox** [comment]
This seems like it would be expected behavior, LXC or not. See https://redis.io/topics/faq#background-saving-fails-with-a-fork-error-under-linux-even-if-i-have-a-lot-of-free-ram and http://curiousthing.org/can-it-fork for deeper dives/explanations as to why a fork can fail. Of specific note from https://www.kernel.org/doc/Documentation/vm/overcommit-accounting is:
>We account mmap memory mappings

rtorrent relies heavily on mmap for file operations.

**Comment by rakshasa** [comment]
Try setting 'pieces.memory.max' to something lower.

Also when you get the fork errors, check the value of 'pieces.memory.current' to see how much mmap'ed memory rtorrent is using.
