### ISSUE TITLE
View based on tracker

### ISSUE THREAD

**Issue by chkiss** [rakshasa/rtorrent#806]
Is it possible to create a view that is based on a tracker without installing any plugins? I would like to view just torrents from my OS or TV tracker, for example.

I tried approaching this problem myself but am having trouble even figuring out why my very first step, "print=$t.url=", doesn't work.

**Comment by chros73** [comment]
That's correct, since [t.*](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#t-commands), [f.*](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#f-commands), [p.*](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#p-commands) commands supposed to be used with their corresponding `*.multicall` commands. In this case with [t.multicall](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#t-commands):
```ini
# print all the tracker urls of a download
t.multicall=$d.hash=,print=$t.url=
```

rtorrent-ps and rtorrent-ps-ch includes `d.tracker_alias` and [d.tracker_domain](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-tracker-alias) commands that can be used e.g. in a view.

**Comment by chkiss** [comment]
Thank you, I'll look into using one of those forks instead.
