### ISSUE TITLE
Remove torrent using xmlrpc commands?

### ISSUE THREAD

**Issue by jbal91** [rakshasa/rtorrent#862]
This doesn't seem to be documented anywhere.

Tried d.close <hash>, d.stop <hash>, d.delete_tied <hash>, remove_untied

Nothing removes anything.

**Comment by kannibalox** [comment]
I think `d.erase` was the solution, but for posterity, what worked for you?

**Comment by jbal91** [comment]
Yep. d.erase did the trick.

**Comment by natethelen** [comment]
After looking at how rutorrent does it from the browser, this is how I ended up getting it to work. Just doing the d.delete_tied and the d.erase didn't seem to work for me. I haven't looked at what d.custom5.set does, yet:

```
hash = "some hash"
system.multicall([
    {"methodName": "d.custom5.set", "params": [hash, "1"]},
    {"methodName": "d.delete_tied", "params": [hash]},
    {"methodName": "d.erase", "params": [hash]},
])
```

**Comment by Jolly-Pirate** [comment]
Here too, I often look at ruTorrent for inspiration. In this case https://github.com/Novik/ruTorrent/blob/cba1bfc11cc8ebc8a3c65d1d37cfbd4d6261a39e/plugins/erasedata/init.js#L54

**Comment by kannibalox** [comment]
Yeah, d.custom5.set doesn't do anything by itself, however the erasedata plugin hooks into `event.download.erased`, and it uses the value custom5 to determine whether to force delete (`1` means no, `2` means yes). If the hook method fails (e.g. because custom5 is unset), the erase event won't happen.
