### ISSUE TITLE
Rtorrent stop while copy to another folder.

### ISSUE THREAD

**Issue by eldire** [rakshasa/rtorrent#877]
Good morning, I would like to know how I can do it so that once the torrent is downloaded, it is automatically copied to another folder. I have tried with the following code, but rtorrent remains stopped until it finishes making the copy. Have you any solution occurs?.

`system.method.insert = d.origen2, simple2, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"

system.method.set_key = event.download.finished,push_me,"execute.nothrow=cp,-R,$d.origen2=,/libreria/"`

**Comment by kannibalox** [comment]
`execute.nothrow` runs in the foreground, in order to have happen in the background you'd need to use `execute.nothrow.bg`, but that also means that the torrent data might not be present in /libreria/ for any of the other completion events you might have, so you might want to put it in a shell script that can handle things properly.
See https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#execute-commands for more info on the `execute.*` commands.

**Comment by rakshasa** [comment]
Essentially the above, might be an idea to make it possible to call commands after a background call is done.

**Comment by DirtyCajunRice** [comment]
@rakshasa this is the current roadblock i have. I have files moving in the background via execute.throw.bg, but there is no way i can tell to wait to do the next step untill the bg process completes (e.g. dont update the completed location for the torrent until its fully there). It fixes the freezing since its done in the background, but brings up other automation issues since it updates the location immediately

**Comment by kannibalox** [comment]
@DirtyCajunRice I'd recommend the PMB method of calling a directory of executable scripts in sequence: https://github.com/pyroscope/pimp-my-box/blob/master/roles/rtorrent-ps/files/bin/_event.download.finished. It happens in the background but also in a predictable order.
