### ISSUE TITLE
rTorrent fail to start

### ISSUE THREAD

**Issue by vinedu18** [rakshasa/rtorrent#903]
hello rtorent dosent start 

root@debian:~# systemctl status rtorrent.service
● rtorrent.service - rTorrent
   Loaded: loaded (/etc/systemd/system/rtorrent.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-08-12 23:09:53 CEST; 4s ago
  Process: 2105 ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent -n -o import=/root/.config/rtorrent/rtorrent.rc (code=exited, status=0/SUCC
  Process: 2109 ExecStop=/usr/bin/killall -w -s 2 /usr/bin/rtorrent (code=exited, status=1/FAILURE)
 Main PID: 2106 (code=exited, status=0/SUCCESS)

août 12 23:09:53 debian systemd[1]: Starting rTorrent...
août 12 23:09:53 debian systemd[1]: Started rTorrent.
août 12 23:09:53 debian killall[2109]: /usr/bin/rtorrent: aucun processus trouvé
août 12 23:09:53 debian systemd[1]: rtorrent.service: Control process exited, code=exited, status=1/FAILURE
août 12 23:09:53 debian systemd[1]: rtorrent.service: Failed with result 'exit-code'.

**Comment by netuddki6** [comment]
I found the solution.
After I changed the config file, I did `sudo service rtorrent restart`
I got the same error.
First: You need to use smaller digits than _2^16 =_ 65536 in rtorrent.rc config file.
And: rutorrent... otherwise apache2 (for me, but can be nginx etc...)was run when I tried to restart rtorrent.
      The problem: rtorrent and rutorrent  use the same port (default 5000). When rtorrent wanted to restart, rutorrent used port 5000. ---> rtorrent coudn't be started because the configured port was busy.
      Solution: First stop rutorrent with
`sudo service apache2 stop`
      Restart rtorrent:
`service rtorrent restart`
      And start rutorrent (web server):
`service apache2 start`

**Comment by kannibalox** [comment]
The bug report posted and your issue bear very little similarity, I hope that future users won't conflate the two.

**Comment by netuddki6** [comment]
> The bug report posted and your issue bear very little similarity, I hope that future users won't conflate the two.

Have you tried it?

**Comment by kannibalox** [comment]
I have not tried starting both rtorrent and rutorrent/apache configured to listen on the same port, because I would expect the same error you encountered. I haven't tried starting any program with a listening port higher than 65536 either, if that's what you meant, because I wouldn't expect that to work either.

**Comment by pyroscope** [comment]
65535 ;)
