### ISSUE TITLE
does rtorrent support uTP?

### ISSUE THREAD

**Issue by rezad1393** [rakshasa/rtorrent#912]
does rtorrent support uTP?
any plan to support it?

**Comment by rakshasa** [comment]
No, uTP hasn't been implemented yet.

Consider donating [donating](https://rakshasa.github.io/rtorrent/donate.html) to help keep this project active.

**Comment by rezad1393** [comment]
this makes it impossible to download from peers that only support that?
I have a bad isp that I know messes with torrent. 
for example I have seen a torrent with one seeder from private tracker that rtorrent cant download all of (it gets stuck in 10%) but transmission downloads it fine.

**Comment by mhertz** [comment]
All clients supporting uTP by default also retries connection in tcp when uTP not available, either they try tcp after utp or both in parallel and see which answer/connect, so normally connectivity shouldn't be an issue(and speed faster actually in practice with tcp), but uTP also support Nat traversal(udp-holepunching) so you sometimes can connect through uTP to otherwise firewalled peers. 

Before transmission enabled libutp Integration then people though also reported these disreprensies between transmission and e.g deluge or other uTP supporting client. 

Try testing that one peer with uTP disabled in transmission also.

**Comment by rezad1393** [comment]
I didnt understand your second paragraph.

the first paragraph makes sense and it seems that program author is too busy to add this feature.

I got my answer from the first paragraph with the udp-holepunching.
I live in iran and internet here is really shitty (not so much speed but the buggy protocol filtering and censorship). LPT:dont live in iran.

**Comment by mhertz** [comment]
Sorry for the confusion  :) I just meant that maybe uTP wasn't the issue(lack thereof), since it was a seeder from private tracker and you got to 10% nonetheless. The "though" in second paragraph was little out of place agreed, but I was referring too that usually there shouldn't be a big issue, and I believe this hole punching isn't very good/efecient, but could of course help when working.

**Comment by rezad1393** [comment]
maybe.
but I have nocticed that transmission client works for torrents with low seeders better than rtorrent.
but maybe that is for me only.
right now I use rtorrent for seeding private trackers and transmission for downloading.
