### ISSUE TITLE
Read past initial payload after incoming encrypted handshake.

### ISSUE THREAD

**Issue by barchan** [rakshasa/rtorrent#942]
Debian 9.11 / rTorrent 0.9.6/0.13.6

Everyday crashes with the same error:

```
1576447072 C Caught internal_error: 'Read past initial payload after incoming encrypted handshake.'.
---DUMP---
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x227) [0x7f1589d16da7]
rtorrent(_ZN7torrent14internal_errorC1EPKc+0xb4) [0x55776ef55884]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xc8664) [0x7f1589db1664]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0x152) [0x7f1589d2e352]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x61) [0x7f1589d2e3f1]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x134) [0x7f1589d6c454]
rtorrent(+0x1fd67) [0x55776ef14d67]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f15884632e1]
rtorrent(+0x21f7a) [0x55776ef16f7a]

---END---
```

Can you help me? How to avoid this problem in the future? Thank you!

**Comment by carldibert** [comment]
adding in since this still is happening with me

> Caught internal_error: 'Read past initial payload after incoming encrypted handshake.'.
---DUMP---
/usr/lib/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x25a) [0x7fd08dc4f89a]
/usr/bin/rtorrent(_ZN7torrent14internal_errorC1EPKc+0xb1) [0x5589ae233db1]
/usr/lib/libtorrent.so.19(+0x3cfe2) [0x7fd08dc44fe2]
/usr/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0xca) [0x7fd08dc6a91a]
/usr/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x79) [0x7fd08dc6aa39]
/usr/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x123) [0x7fd08dc9b583]
/usr/bin/rtorrent(+0x4542c) [0x5589ae1d642c]
/usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7fd08d823002]
/usr/bin/rtorrent(+0x45c6e) [0x5589ae1d6c6e]

---END---

**Comment by kannibalox** [comment]
Please try the latest version before submitting issues if possible, https://github.com/rakshasa/libtorrent/pull/99 has already changed libtorrent to handle that error less drastically.
