### ISSUE TITLE
Is rtorrent multicore?

### ISSUE THREAD

**Issue by TapuGithub** [rakshasa/rtorrent#991]
Hello,

It's more a question than a bug.
I have weak dual core CPU(439 passmarks per core) and fast internet(up to 1GBit/s). Transmission currently can write up to 150-200 MBit/s utilising one core. 
Could it be better with rtorrent? Can it use both cores?

**Comment by DrMythnick** [comment]
- docker > 2 containers with different settings > manual multicore

**Comment by TapuGithub** [comment]
@DrMythnick possible, thanks.

**Comment by kannibalox** [comment]
useless question, please close

**Comment by stastnypremysl** [comment]
I don't think, it is useless question. It would be nice, if there was something like -j N option.

**Comment by PulsedMedia** [comment]
rTorrent is very very lightly multithreaded, in essence your bottleneck is still single core and clock frequency matters above anything else.

Best way to get highest speeds are multiple instances.

**Comment by rakshasa** [comment]
It's more an issue of IO bandwidth, however certain things are threaded like hash checking.

**Comment by PulsedMedia** [comment]
Jari Sundell,

Thank you for contacting our support team. Your ticket has been opened, and you will be notified by e-mail upon response.


FIRST STEPS FOR RESOLUTION

Check the http://pulsedmedia.com/clients/knowledgebase.php
If technical error: Clear browser cache and re-try, make certain you have full error message in your ticket for swift resolution.

This solved your problem? You may close your ticket from http://pulsedmedia.com/clients/


Please, be thorough in your tickets, what error message(s) you received, what you were specifically trying to do. General vague "there is an error while logging in" will not allow us to swiftly solve this ticket, please be precise, a good example is: "Using FTP it gives me username/password denied error, but i can login fine via http on the gui". Include what you saw, what you expected to see, and since when this has been happening.

If you did not detail your issue, please reply to this e-mail with details: What were you expecting to see, what did you actually get, how did this happen and how long has this been going on.




Details of your ticket:
Subject: Re: [rakshasa/rtorrent] Is rtorrent multicore? (#991)
Priority: Medium
Status: Open
Estimated 1st reply: within 12hours.

You can view the ticket at any time at https://pulsedmedia.com/clients/viewticket.php?tid=525112&c=YXcMxPGQ

 

Need help instantly?

Did you check our http://wiki.pulsedmedia.com

Pulsed Media - Modern content distribution services

**Comment by PulsedMedia** [comment]
Jari Sundell,

Thank you for contacting our support team. Your ticket has been opened, and you will be notified by e-mail upon response.


FIRST STEPS FOR RESOLUTION

Check the http://pulsedmedia.com/clients/knowledgebase.php
If technical error: Clear browser cache and re-try, make certain you have full error message in your ticket for swift resolution.

This solved your problem? You may close your ticket from http://pulsedmedia.com/clients/


Please, be thorough in your tickets, what error message(s) you received, what you were specifically trying to do. General vague "there is an error while logging in" will not allow us to swiftly solve this ticket, please be precise, a good example is: "Using FTP it gives me username/password denied error, but i can login fine via http on the gui". Include what you saw, what you expected to see, and since when this has been happening.

If you did not detail your issue, please reply to this e-mail with details: What were you expecting to see, what did you actually get, how did this happen and how long has this been going on.




Details of your ticket:
Subject: Re: [rakshasa/rtorrent] Is rtorrent multicore? (#991)
Priority: Medium
Status: Open
Estimated 1st reply: within 12hours.

You can view the ticket at any time at https://pulsedmedia.com/clients/viewticket.php?tid=635371&c=sA41Dc0w

 

Need help instantly?

Did you check our http://wiki.pulsedmedia.com

Pulsed Media - Modern content distribution services

**Comment by PulsedMedia** [comment]
> It's more an issue of IO bandwidth, however certain things are threaded like hash checking.

Actually it is not. Remember the performance metrics we have sent to you half a year ago?
Even a 24 drive server or NVMe array will not run any faster than certain speed on single instance. Only CPU clockspeed seems to matter due to the polling & locking methodology in rtorrent and therefore being limited to single thread managing it all underneath. After that only thing that can boost performance is multiple instances.

We did throw at it an 32core CPU with 256gb ram, 24x drives for just single instance. Only CPU clock speed seemed to matter beyond certain point. It becomes a function of how many connections, torrents etc. are and averages to the swarm speed essentially, if swarm could accept faster, make less connections etc. to ensure rtorrent is not bottlenecking.

Did you ignore all those reports or even read them?

**Comment by kannibalox** [comment]
My first response was reactionary and worse than the uselessness I claimed the the OP was, so apologies for that. Is were any way you can post the metrics in question? Despite my rudeness, I don't think rakshasa has ignored very many legit bug reports.
